Homework2
Ksenia-Dugushova/MathMech_Lesson pull request #2
Opened 2022-11-02 20:16 UTC by Ksenia-Dugushova

The second homework.

The second homework consists of 3 functions:
1)BubbleSort (Sorts the list using Bubble Sort algorithm)
2)QuickSort (Sorting the list with Quicksort algorithm)
3)Concatenation (Combines two lists into one)

Functions are implemented for 2 types (MyList and OOPList).

2022-11-03 09:46 UTC, gsvgit requested changes
Что-то у Вас код какой-то лоскутный. Как будто из разных кусочков его собрали.

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/Hw2.fs
> +let bubbleSort array =
А это что такое? В домашке, вроде, было про списки.

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/Main.fs
>  module Main =
А зачем два Main-а?

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/MyList.fs
> +let rec sortList (lst: MyList<'value>) a =
А почему название функции не соответствует комментарию (и тому, что она делает)

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/OOPList.fs
> +let rec MO (lst: MyList<'value>) =
Очент "говорящее" название функции

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/OOPList.fs
> +let rec OM (lst: OOPList<'value>) =
И это тоже

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/OOPList.fs
> +let BubbleSort (lst: OOPList<'value>) =
А почему стриль имён так "скачет"?

2022-11-03 09:46 UTC, gsvgit commented on src/MathMech_Lessons/OOPList.fs
> +        if
Вау. Откуда такое форматирование?

2022-11-16 16:51 UTC, gsvgit requested changes

2022-11-16 16:51 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/File1.fs
> +﻿open Android.App
А это что за зверь такой?

2022-11-16 16:51 UTC, gsvgit commented on src/MathMech_Lessons/OOPList.fs
> +let rec sortList (lst: OOPList<'value>) a =
А почему название функции такое странное. Она же просто режет лисн на части.

2022-11-16 16:51 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Tests.fs
> +module MyList =
Тесты на свойства добавьте пожалуйста.

2022-11-22 12:51 UTC, Ksenia-Dugushova commented on src/MathMech_Lessons/OOPList.fs
> +        if
fantomas так сформатировал

2022-11-25 08:54 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Tests.fs
> +                <| MyListHW.bubbleSort (lst)
А зачем тут скобки?

2022-11-25 08:54 UTC, gsvgit approved these changes

2022-11-27 13:35 UTC, merged