the 1 version
Ksenia-Dugushova/MathMech_Lesson pull request #4
Opened 2022-12-21 16:04 UTC by Ksenia-Dugushova

Домашняя работа 4
1. Используя алгебраические типы данных реализовать деревья, необходимые для представления разреженных матриц и разреженных векторов
2. Реализовать тип "вектор" и тип "матрица" с использованием реализованных ранее деревьев
3. Реализовать функцию умножения вектора на матрицу

2022-12-22 06:53 UTC, gsvgit requested changes

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/MultiMatrix.fs
> +    (multiOperation: 'value1 option -> 'value2 option -> 'value3 option)
А зачем то использовать угловые скобки, то не использовать?

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/SparseMatrix.fs
> +        val Keeping: QuadTree<'value>
Ой... Очень странное имя для поля.

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/SparseMatrix.fs
> +        val LengthR: int
RowCount, видимо? Тоже странные имена.

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/SparseMatrix.fs
> +        val LengthSquare: int
А это кто такой?

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/SparseMatrix.fs
> +                                && b
Боль какая-то подкрутите настройки Фантомаса.

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/SparseVector.fs
> +let operation
Кто? Тоже с именем проблемы.

2022-12-22 06:53 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +                let arr' = Array.append arr [| Some(1) |]
Что? Что-то странное происходит. Ну взяли сразу пришежший массив и попробовали из него элемент достать. Зачем что-то куда-то преобразовывать?

2022-12-22 06:53 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +                let arr' =
И тут тоже что-то странное.

2022-12-22 06:53 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +                             - 1 do
И тут какая-то боль с форматированием. Надо точно подкрутить настройки.

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/MultiMatrix.fs
> +    let rec makingBinareTree (tree: BinaryTree<'vslue>) desiredSize splitSize =
Опечатка в имени?

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/MultiMatrix.fs
> +    let rec makingBinareTree (tree: BinaryTree<'vslue>) desiredSize splitSize =
Или даже оно вообще странное. Судя по аргументам, что-то не то, что в имени тут происходит

2022-12-22 06:53 UTC, gsvgit commented on src/MathMech_Lessons/MultiMatrix.fs
> +                splitBinaryTree makeTree desiredSize matrix.LengthSquare
И сплит, похоже, не сплит.

2022-12-23 18:23 UTC, Ksenia-Dugushova commented
fantomasignore только для тех файлов, которые не относятся к этому дз, чтобы PR не "засорять"

2022-12-24 06:46 UTC, gsvgit reviewed
А чтобы в реквест не попадоли лишние файлы лучше сперва их выложить. Тогда не надо будет объяснять, зачем Вы игнорите кучу файлов.

2022-12-24 06:46 UTC, gsvgit commented on src/MathMech_Lessons/SparseMatrix.fs
> +        val LengthSquare: int
И всё же. Кто такой `LengthSquare` ?

2022-12-24 06:46 UTC, gsvgit commented on src/MathMech_Lessons/SparseVector.fs
> +        val LengthSquare: int
Кто такой `LengthSquare`?

2022-12-24 06:46 UTC, gsvgit commented on src/MathMech_Lessons/SparseVector.fs
> +let addVector (fPlus: 'value1 option -> 'value2 option -> 'value3 option) (vector1: SparseVector<'value1>) (vector2: SparseVector<'value2>) : SparseVector<'value3> =
А тут снова без угловых скобочек. Проверьте, пожалуйста, чтобы во всём коде стиль единый был.

2022-12-24 06:46 UTC, gsvgit commented on src/MathMech_Lessons/SparseVector.fs
> +    let rec operationTree tree1 tree2 =
operationTree --- это про что-то другое. Не про то, что здесь происходит.

2022-12-24 06:46 UTC, gsvgit commented on src/MathMech_Lessons/SparseVector.fs
> +        val LengthSquare: int
И зачем он нужен.

2022-12-24 06:46 UTC, gsvgit commented on src/MathMech_Lessons/SparseVector.fs
> +            | BinaryTree.None -> BinaryTree.None
Дублирование наблюдается. Обработка пары из двух None два раза описана.

2022-12-24 06:46 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +                  let naiveAddition (arr1: array<Option<int>>) (arr2: array<Option<int>>) =
Идея хорошая. Но есть map2

2022-12-24 06:46 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +        | Some x, Some y -> Some(x + y)
А что будет, если в результате сложения мы получм "ноль", который не надо хранить?

2022-12-24 06:46 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +        | Some x, Some y -> Some(x * y)
А что будет, если в результате умножения мы получм "ноль", который не надо хранить?

2022-12-26 08:01 UTC, gsvgit reviewed
Не очень понял. Кажется, на некоторые замечания ничего не изменилось.

2022-12-26 08:01 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +                  let naiveAddition (arr1: array<Option<int>>) (arr2: array<Option<int>>) =
А где map2? И ещё, кажется, в паре мест его можно применить.

2022-12-26 08:01 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +        | Some x, Some y -> Some(x + y)
Кажется, ничего не поменялось

2022-12-26 14:19 UTC, Ksenia-Dugushova commented
была ошибка с push, сейчас изменения подтянулись

2022-12-27 08:38 UTC, gsvgit commented
Всё ещё не вижу правок к части комментариев. В частности, в тестах.

2022-12-27 09:21 UTC, Ksenia-Dugushova commented on tests/MathMech_Lessons.Tests/Test4.fs
> +        | Some x, Some y -> if x + y <> 0 then Some(x + y) else Option.None
[https://github.com/Ksenia-Dugushova/MathMech_Lessons/pull/4#discussion_r1056752235](url) 
Решение данной проблемы

2022-12-27 12:46 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test4.fs
> +                      for i in 0 .. (abs length) - 1 do
Кажется, это map2.

2022-12-28 12:42 UTC, gsvgit approved these changes

2022-12-31 20:28 UTC, merged