1 v
Ksenia-Dugushova/MathMech_Lesson pull request #8
Opened 2023-01-02 17:15 UTC by Ksenia-Dugushova

2023-01-03 06:34 UTC, gsvgit requested changes

2023-01-03 06:34 UTC, gsvgit commented on src/MathMech_Lessons/BFS.fs
> +    | Some value, _ -> Some value
Можно короче записать

2023-01-03 06:34 UTC, gsvgit commented on src/MathMech_Lessons/BFS.fs
> +    | Some value, Option.None -> Some value
Это тоже можно короче сделать

2023-01-03 06:34 UTC, gsvgit commented on src/MathMech_Lessons/BFS.fs
> +    | _ -> failwith $"Something wrong with SuperSum"
А что wrong?

2023-01-03 06:34 UTC, gsvgit commented on src/MathMech_Lessons/BFS.fs
> +let BFS (graph: SparseMatrix<'value>) (apexes: list<uint>) =
Странное в данном контексте слово apexes. Что оно тут значит?

2023-01-03 06:34 UTC, gsvgit commented on src/MathMech_Lessons/BFS.fs
> +    let front = SparseVector(apexes, graph.ColumnCount)
Хотите я скажу, с кого Вы срисовали такое решение для инициализации этих двух векторов?

2023-01-03 06:34 UTC, gsvgit commented on src/MathMech_Lessons/SparseMatrix.fs
> +    let rec quadTreeFormation list length =
И тоже что-то очень знакомое. давайте Вы для профилактики сделаете ещё и parentBFS. Это такой же BFS, только в результирующем векторе v[i] --- это номер вершины предка в порядке обхода.

2023-01-03 06:34 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test5.fs
> +                                      ()
Вот тут можно короче.

2023-01-03 06:34 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/Test5.fs
> +                              helper (result @ [ x ]) (visited.Add(fst x))
Воу. А можно ли как-то экономичнее? А то добавлять каждый раз всего один элемент в конец списка --- очень затратное действие.

2023-01-06 20:31 UTC, gsvgit requested changes

2023-01-06 20:31 UTC, gsvgit commented on src/MathMech_Lessons/BFSparent.fs
> +let mult x y =
А зачем дублировать код?

2023-01-09 08:11 UTC, gsvgit requested changes

2023-01-09 08:11 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +module SayTests =
А что за название модуля странное?

2023-01-09 08:11 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                      [ (0u, 1u, Some 4); (1u, 0u, Some 4); (1u, 3u, Some 9); (3u, 1u, Some 9) ]
Что является значениями в матрице? Какие-то они странные.

2023-01-09 08:11 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                  let actualResult = parentBFS matrix [ 0u; 1u; 2u; 3u ]
Ща. Если я правильно понимаю, у Вас в графе вообще нет рёбер из вершины 2. Как она может быть предком кого-то в порядке обхода? Она же получается просто изолированной вершиной.

2023-01-11 11:07 UTC, Ksenia-Dugushova commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                      [ (0u, 1u, Some 4); (1u, 0u, Some 4); (1u, 3u, Some 9); (3u, 1u, Some 9) ]
Не совсем понимаю, что в них странного

2023-01-11 11:07 UTC, Ksenia-Dugushova commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                  let actualResult = parentBFS matrix [ 0u; 1u; 2u; 3u ]
стартовые вершины сами для себя предки

2023-01-12 12:45 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                      [ (0u, 1u, Some 4); (1u, 0u, Some 4); (1u, 3u, Some 9); (3u, 1u, Some 9) ]
Кто такой `Some 4`?

2023-01-12 12:52 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                  <| Node(Node(Node(Leaf 0u, Leaf 1u), Node(Leaf 2u, Leaf 3u)), Node(Node(Leaf 0u, Leaf 1u), Node(Leaf 2u, Leaf 3u)))
А так правда удобнее, чем просто задать руками массив, а потом вызвать функцю, которая сама его в дерево превратит? Или даже просто реальный результат в обычный массив превратить? Думаю, гораздо проще читать будет.

2023-01-12 12:52 UTC, gsvgit commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                  let naiveParentBFS start (arr: 'a option[,]) =
Правда ли, что нельзя обобщить наивные реализации разных BFS? Больно они похожи.

2023-01-15 22:28 UTC, Ksenia-Dugushova commented on tests/MathMech_Lessons.Tests/TestBFSparent.fs
> +                      [ (0u, 1u, Some 4); (1u, 0u, Some 4); (1u, 3u, Some 9); (3u, 1u, Some 9) ]
Значение на ребре графа

2023-01-16 07:17 UTC, gsvgit approved these changes
Но коммиты после реквеста --- дурная затя.

2023-01-16 22:59 UTC, merged